apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels: {app: payment}
  template:
    metadata:
      labels: {app: payment}
    spec:
      containers:
        - name: payment
          image: ghcr.io/shashank460/ecommerce-payment:latest
          ports:
            - {containerPort: 8080, name: health}
          envFrom:
            - {configMapRef: {name: ecommerce-config}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels: {app: notification}
  template:
    metadata:
      labels: {app: notification}
    spec:
      containers:
        - name: notification
          image: ghcr.io/shashank460/ecommerce-notification:latest
          ports:
            - {containerPort: 8080, name: health}
          envFrom:
            - {configMapRef: {name: ecommerce-config}}
