import express from 'express';import jwt from 'jsonwebtoken';import {randomUUID} from 'node:crypto';import {collectDefaultMetrics,Counter,Registry} from 'prom-client';
const app=express();app.use(express.json());const secret=process.env.JWT_SECRET||'dev-secret';const registry=new Registry();collectDefaultMetrics({register:registry});const requests=new Counter({name:'gateway_requests_total',help:'Gateway requests',registers:[registry]});
app.use((req,res,next)=>{requests.inc();res.setHeader('x-request-id',req.header('x-request-id')||randomUUID());next()});app.get('/health',(_,res)=>res.json({status:'ok',service:'gateway'}));app.get('/metrics',async(_,res)=>{res.setHeader('content-type',registry.contentType);res.end(await registry.metrics())});
const openapi={openapi:'3.0.3',info:{title:'E-Commerce Order Processing API',version:'1.0.0',description:'Gateway contract for the distributed order-processing system.'},servers:[{url:'http://localhost:3000'}],components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer',bearerFormat:'JWT'}},schemas:{Order:{type:'object',properties:{id:{type:'string'},status:{type:'string'}}}}},paths:{'/auth/token':{post:{summary:'Issue demo JWT',requestBody:{required:true,content:{'application/json':{schema:{type:'object',properties:{userId:{type:'string'}}}}}},responses:{'200':{description:'JWT token'}}}},'/products':{get:{summary:'List products',responses:{'200':{description:'Product response'}}},post:{summary:'Create product',security:[{bearerAuth:[]}],responses:{'201':{description:'Created'}}}},'/orders':{post:{summary:'Create an order',security:[{bearerAuth:[]}],parameters:[{in:'header',name:'Idempotency-Key',required:true,schema:{type:'string'}}],requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['userId','items'],properties:{userId:{type:'string'},items:{type:'array',items:{type:'object',properties:{productId:{type:'integer'},quantity:{type:'integer'}}}}}}}}},responses:{'201':{description:'Order created'},'409':{description:'Order conflict'}}}}}};
app.get('/api-docs.json',(_,res)=>res.json(openapi));app.get('/api-docs',(_,res)=>res.type('html').send(`<!doctype html><html><head><title>API Docs</title><link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist/swagger-ui.css"></head><body><div id="swagger-ui"></div><script src="https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"></script><script>SwaggerUIBundle({url:'/api-docs.json',dom_id:'#swagger-ui'})</script></body></html>`));
app.post('/auth/token',(req,res)=>{const userId=String(req.body?.userId||'demo-user');res.json({token:jwt.sign({sub:userId,role:'customer'},secret,{expiresIn:'1h'})})});
function auth(req:any,res:any,next:any){const h=req.header('authorization');if(!h?.startsWith('Bearer '))return res.status(401).json({error:'missing bearer token'});try{req.user=jwt.verify(h.slice(7),secret);next()}catch{return res.status(401).json({error:'invalid token'})}}
async function proxy(req:any,res:any,url:string){try{const headers:any={'content-type':'application/json','x-request-id':res.getHeader('x-request-id')};const r=await fetch(url+req.originalUrl,{method:req.method,headers,body:['GET','HEAD'].includes(req.method)?undefined:JSON.stringify(req.body)});const text=await r.text();res.status(r.status).type(r.headers.get('content-type')||'application/json').send(text)}catch{res.status(503).json({error:'upstream unavailable'})}}
app.use('/products',(req,res)=>proxy(req,res,process.env.PRODUCT_URL||'http://localhost:3001'));app.use('/orders',auth,(req,res)=>proxy(req,res,process.env.ORDER_URL||'http://localhost:3002'));app.listen(Number(process.env.PORT||3000),()=>console.log('gateway listening'));
